services:
  backend:
    build: ./backend
    container_name: backend
    secrets:
      - cerebras_api_key
      - exa_api_key
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    command: ["sleep", "infinity"]

secrets:
  cerebras_api_key:
    file: ./backend/api_keys/cerebras_api_key
  exa_api_key:
    file: ./backend/api_keys/exa_api_key
